### ISSUE TITLE
UI - Retire Beverage

### ISSUE THREAD

**Issue by AnthonyWhitakerJr** [mcadamss1/STAGBAR#17]
Display all active beverages and allow user to select which ones to retire. 
Retiring an alcohol adds a retire date for that alcohol to the database.
Retiring a drink simply marks it as retired.
Drinks can be unretired, alcohol cannot.

**Comment by AnthonyWhitakerJr** [comment]
Notify user if they attempt to retire a alcohol that is an ingredient to an active drink.
Notify user if they attempt to un-retire a drink with retired ingredients.

**Comment by AnthonyWhitakerJr** [comment]
This should be implemented as 2 separate UIs. One for Alcohol & one for drinks.

**Comment by AnthonyWhitakerJr** [comment]
Any update on this issue???

**Comment by kansai2kansas** [comment]
So I helped out with creating the RetireAlcoholUI, and pushed my code. Please have a look at it.

The UI itself works just fine, but retiring Alcohol never works because when each Alcohol was initially created with CreateAlcoholUI, they are always given Alcoholid of -1. The auto-increment of Alcoholid which is supposed to happen inside data.Alcohol.java has not happened. Therefore, there is no unique identifier for any of the given alcohols and retiring any of the alcohols have no effect whatsoever...
